# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1520, 905)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.movieGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieGroupBox.sizePolicy().hasHeightForWidth())
        self.movieGroupBox.setSizePolicy(sizePolicy)
        self.movieGroupBox.setMinimumSize(QtCore.QSize(500, 500))
        self.movieGroupBox.setMaximumSize(QtCore.QSize(800, 3000))
        self.movieGroupBox.setObjectName("movieGroupBox")
        self.verticalLayout_4.addWidget(self.movieGroupBox)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.imageSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageSlider.sizePolicy().hasHeightForWidth())
        self.imageSlider.setSizePolicy(sizePolicy)
        self.imageSlider.setMaximumSize(QtCore.QSize(500, 16777215))
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setObjectName("imageSlider")
        self.horizontalLayout_14.addWidget(self.imageSlider)
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.doFit = QtWidgets.QPushButton(self.centralwidget)
        self.doFit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doFit.setObjectName("doFit")
        self.horizontalLayout_14.addWidget(self.doFit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.rangeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.rangeGroupBox.setMaximumSize(QtCore.QSize(800, 80))
        self.rangeGroupBox.setObjectName("rangeGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rangeGroupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minSpinBox = QtWidgets.QSpinBox(self.rangeGroupBox)
        self.minSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.minSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.minSpinBox.setMaximum(5000)
        self.minSpinBox.setProperty("value", 100)
        self.minSpinBox.setObjectName("minSpinBox")
        self.horizontalLayout_6.addWidget(self.minSpinBox)
        self.rangeSliderWidget = QtWidgets.QWidget(self.rangeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSliderWidget.sizePolicy().hasHeightForWidth())
        self.rangeSliderWidget.setSizePolicy(sizePolicy)
        self.rangeSliderWidget.setMinimumSize(QtCore.QSize(30, 50))
        self.rangeSliderWidget.setMaximumSize(QtCore.QSize(300, 50))
        self.rangeSliderWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rangeSliderWidget.setObjectName("rangeSliderWidget")
        self.horizontalLayout_6.addWidget(self.rangeSliderWidget)
        self.maxSpinBox = QtWidgets.QSpinBox(self.rangeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxSpinBox.sizePolicy().hasHeightForWidth())
        self.maxSpinBox.setSizePolicy(sizePolicy)
        self.maxSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.maxSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.maxSpinBox.setMaximum(6000)
        self.maxSpinBox.setProperty("value", 1000)
        self.maxSpinBox.setObjectName("maxSpinBox")
        self.horizontalLayout_6.addWidget(self.maxSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addWidget(self.rangeGroupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nmPerPixLabel = QtWidgets.QLabel(self.centralwidget)
        self.nmPerPixLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nmPerPixLabel.setObjectName("nmPerPixLabel")
        self.horizontalLayout_2.addWidget(self.nmPerPixLabel)
        self.nmPerPixelSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.nmPerPixelSpinBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nmPerPixelSpinBox.setMaximum(1000.0)
        self.nmPerPixelSpinBox.setProperty("value", 160.0)
        self.nmPerPixelSpinBox.setObjectName("nmPerPixelSpinBox")
        self.horizontalLayout_2.addWidget(self.nmPerPixelSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.frameLabel = QtWidgets.QLabel(self.centralwidget)
        self.frameLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.frameLabel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frameLabel.setObjectName("frameLabel")
        self.horizontalLayout_2.addWidget(self.frameLabel)
        self.xyiLabel = QtWidgets.QLabel(self.centralwidget)
        self.xyiLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.xyiLabel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.xyiLabel.setScaledContents(False)
        self.xyiLabel.setObjectName("xyiLabel")
        self.horizontalLayout_2.addWidget(self.xyiLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.analyze_current_dax = QtWidgets.QPushButton(self.centralwidget)
        self.analyze_current_dax.setObjectName("analyze_current_dax")
        self.horizontalLayout_15.addWidget(self.analyze_current_dax)
        self.batch_dax = QtWidgets.QPushButton(self.centralwidget)
        self.batch_dax.setObjectName("batch_dax")
        self.horizontalLayout_15.addWidget(self.batch_dax)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLabel.sizePolicy().hasHeightForWidth())
        self.fileLabel.setSizePolicy(sizePolicy)
        self.fileLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.fileLabel.setMaximumSize(QtCore.QSize(800, 16777215))
        self.fileLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout_4.addWidget(self.fileLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_stormfinder = QtWidgets.QWidget()
        self.tab_stormfinder.setObjectName("tab_stormfinder")
        self.localization_groupbox = QtWidgets.QGroupBox(self.tab_stormfinder)
        self.localization_groupbox.setGeometry(QtCore.QRect(20, 0, 650, 783))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localization_groupbox.sizePolicy().hasHeightForWidth())
        self.localization_groupbox.setSizePolicy(sizePolicy)
        self.localization_groupbox.setMinimumSize(QtCore.QSize(650, 0))
        self.localization_groupbox.setMaximumSize(QtCore.QSize(800, 16777215))
        self.localization_groupbox.setObjectName("localization_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.localization_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.localization_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 300))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 500))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 766, 448))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(10, 0, 0, 10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fit_fittype = QtWidgets.QComboBox(self.formLayoutWidget)
        self.fit_fittype.setObjectName("fit_fittype")
        self.fit_fittype.addItem("")
        self.fit_fittype.addItem("")
        self.fit_fittype.addItem("")
        self.fit_fittype.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_fittype)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fit_threshold = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_threshold.setObjectName("fit_threshold")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fit_threshold)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fit_maxiter = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_maxiter.setObjectName("fit_maxiter")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fit_maxiter)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fit_ccdbkg = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_ccdbkg.setObjectName("fit_ccdbkg")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fit_ccdbkg)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fit_pixsize = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_pixsize.setObjectName("fit_pixsize")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fit_pixsize)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fit_camgain = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_camgain.setObjectName("fit_camgain")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fit_camgain)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.fit_bkgsig = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_bkgsig.setObjectName("fit_bkgsig")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fit_bkgsig)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fit_initfitwidth = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_initfitwidth.setObjectName("fit_initfitwidth")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fit_initfitwidth)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.fit_maxfindrad = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_maxfindrad.setObjectName("fit_maxfindrad")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.fit_maxfindrad)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.fit_descriptor = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_descriptor.setObjectName("fit_descriptor")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.fit_descriptor)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.fit_maxdisp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_maxdisp.setObjectName("fit_maxdisp")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.fit_maxdisp)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.fit_startframe = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_startframe.setObjectName("fit_startframe")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.fit_startframe)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.fit_endframe = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.fit_endframe.setObjectName("fit_endframe")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.fit_endframe)
        self.formLayoutWidget.raise_()
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.localization_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 131, 81))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.fit_xmin = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_xmin.sizePolicy().hasHeightForWidth())
        self.fit_xmin.setSizePolicy(sizePolicy)
        self.fit_xmin.setMinimumSize(QtCore.QSize(25, 0))
        self.fit_xmin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fit_xmin.setObjectName("fit_xmin")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_xmin)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.fit_xmax = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.fit_xmax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fit_xmax.setObjectName("fit_xmax")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_xmax)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(150, 30, 160, 81))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.fit_ymin = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.fit_ymin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fit_ymin.setObjectName("fit_ymin")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_ymin)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.fit_ymax = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.fit_ymax.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fit_ymax.setObjectName("fit_ymax")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_ymax)
        self.gridLayout_4.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.localization_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 171, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.fit_correctdrift = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.fit_correctdrift.setText("")
        self.fit_correctdrift.setObjectName("fit_correctdrift")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_correctdrift)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.fit_dscale = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.fit_dscale.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fit_dscale.setObjectName("fit_dscale")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_dscale)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.fit_frameperstep = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.fit_frameperstep.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fit_frameperstep.setObjectName("fit_frameperstep")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fit_frameperstep)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(190, 30, 101, 71))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_40.setObjectName("label_40")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.fit_correctz = QtWidgets.QCheckBox(self.formLayoutWidget_8)
        self.fit_correctz.setText("")
        self.fit_correctz.setObjectName("fit_correctz")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_correctz)
        self.groupBox_2.raise_()
        self.formLayoutWidget_2.raise_()
        self.formLayoutWidget_8.raise_()
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.zfit_groupbox = QtWidgets.QGroupBox(self.localization_groupbox)
        self.zfit_groupbox.setMaximumSize(QtCore.QSize(320, 16777215))
        self.zfit_groupbox.setObjectName("zfit_groupbox")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.zfit_groupbox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 271, 121))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.fit_do3dfit = QtWidgets.QCheckBox(self.formLayoutWidget_5)
        self.fit_do3dfit.setText("")
        self.fit_do3dfit.setObjectName("fit_do3dfit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_do3dfit)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.fit_zcutoff = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.fit_zcutoff.setObjectName("fit_zcutoff")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_zcutoff)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.fit_zcalibstart = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.fit_zcalibstart.setObjectName("fit_zcalibstart")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fit_zcalibstart)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.fit_zcalibend = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.fit_zcalibend.setObjectName("fit_zcalibend")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fit_zcalibend)
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.zfit_groupbox)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 160, 122, 231))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_25.setObjectName("label_25")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_26.setObjectName("label_26")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_30.setObjectName("label_30")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_31.setObjectName("label_31")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.fit_wxo = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_wxo.setObjectName("fit_wxo")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_wxo)
        self.fit_gx = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_gx.setObjectName("fit_gx")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_gx)
        self.fit_zrx = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_zrx.setObjectName("fit_zrx")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fit_zrx)
        self.fit_ax = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_ax.setObjectName("fit_ax")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fit_ax)
        self.fit_bx = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_bx.setObjectName("fit_bx")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fit_bx)
        self.fit_cx = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_cx.setObjectName("fit_cx")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fit_cx)
        self.fit_dx = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        self.fit_dx.setObjectName("fit_dx")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fit_dx)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.zfit_groupbox)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(150, 160, 122, 231))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_32.setObjectName("label_32")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_33.setObjectName("label_33")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_34.setObjectName("label_34")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_35.setObjectName("label_35")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_36.setObjectName("label_36")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_37.setObjectName("label_37")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_38.setObjectName("label_38")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.fit_wyo = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_wyo.setObjectName("fit_wyo")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fit_wyo)
        self.fit_gy = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_gy.setObjectName("fit_gy")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fit_gy)
        self.fit_zry = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_zry.setObjectName("fit_zry")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fit_zry)
        self.fit_ay = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_ay.setObjectName("fit_ay")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fit_ay)
        self.fit_by = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_by.setObjectName("fit_by")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fit_by)
        self.fit_cy = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_cy.setObjectName("fit_cy")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fit_cy)
        self.fit_dy = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.fit_dy.setObjectName("fit_dy")
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fit_dy)
        self.fit_save = QtWidgets.QPushButton(self.zfit_groupbox)
        self.fit_save.setGeometry(QtCore.QRect(150, 470, 110, 32))
        self.fit_save.setObjectName("fit_save")
        self.fit_load = QtWidgets.QPushButton(self.zfit_groupbox)
        self.fit_load.setGeometry(QtCore.QRect(30, 470, 110, 32))
        self.fit_load.setObjectName("fit_load")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.zfit_groupbox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 400, 271, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_39 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_11.addWidget(self.label_39)
        self.fit_zcalibstring = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.fit_zcalibstring.setMaximumSize(QtCore.QSize(500, 16777215))
        self.fit_zcalibstring.setObjectName("fit_zcalibstring")
        self.horizontalLayout_11.addWidget(self.fit_zcalibstring)
        self.importZcalibstring = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.importZcalibstring.setObjectName("importZcalibstring")
        self.horizontalLayout_11.addWidget(self.importZcalibstring)
        self.gridLayout_4.addWidget(self.zfit_groupbox, 0, 1, 3, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_stormfinder, "")
        self.tab_localizations = QtWidgets.QWidget()
        self.tab_localizations.setObjectName("tab_localizations")
        self.groupBox = QtWidgets.QGroupBox(self.tab_localizations)
        self.groupBox.setGeometry(QtCore.QRect(20, 0, 250, 781))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.locs1Label = QtWidgets.QLabel(self.groupBox)
        self.locs1Label.setObjectName("locs1Label")
        self.verticalLayout_9.addWidget(self.locs1Label)
        self.locs1TableWidget = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locs1TableWidget.sizePolicy().hasHeightForWidth())
        self.locs1TableWidget.setSizePolicy(sizePolicy)
        self.locs1TableWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.locs1TableWidget.setShowGrid(True)
        self.locs1TableWidget.setObjectName("locs1TableWidget")
        self.locs1TableWidget.setColumnCount(0)
        self.locs1TableWidget.setRowCount(0)
        self.locs1TableWidget.horizontalHeader().setVisible(False)
        self.locs1TableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.locs1TableWidget.horizontalHeader().setStretchLastSection(True)
        self.locs1TableWidget.verticalHeader().setVisible(False)
        self.locs1TableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_9.addWidget(self.locs1TableWidget)
        self.locs2Label = QtWidgets.QLabel(self.groupBox)
        self.locs2Label.setObjectName("locs2Label")
        self.verticalLayout_9.addWidget(self.locs2Label)
        self.locs2TableWidget = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.locs2TableWidget.sizePolicy().hasHeightForWidth())
        self.locs2TableWidget.setSizePolicy(sizePolicy)
        self.locs2TableWidget.setShowGrid(True)
        self.locs2TableWidget.setObjectName("locs2TableWidget")
        self.locs2TableWidget.setColumnCount(0)
        self.locs2TableWidget.setRowCount(0)
        self.locs2TableWidget.horizontalHeader().setVisible(False)
        self.locs2TableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.locs2TableWidget.horizontalHeader().setStretchLastSection(True)
        self.locs2TableWidget.verticalHeader().setVisible(False)
        self.locs2TableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_9.addWidget(self.locs2TableWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_localizations, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1520, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Movie = QtWidgets.QAction(MainWindow)
        self.actionLoad_Movie.setObjectName("actionLoad_Movie")
        self.actionLoad_Locs2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Locs2.setObjectName("actionLoad_Locs2")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad_Locs1 = QtWidgets.QAction(MainWindow)
        self.actionLoad_Locs1.setObjectName("actionLoad_Locs1")
        self.actionCapture = QtWidgets.QAction(MainWindow)
        self.actionCapture.setObjectName("actionCapture")
        self.actionLoad_Parameters = QtWidgets.QAction(MainWindow)
        self.actionLoad_Parameters.setObjectName("actionLoad_Parameters")
        self.actionSave_Parameters = QtWidgets.QAction(MainWindow)
        self.actionSave_Parameters.setObjectName("actionSave_Parameters")
        self.actionSet_DaoSTORM_path = QtWidgets.QAction(MainWindow)
        self.actionSet_DaoSTORM_path.setObjectName("actionSet_DaoSTORM_path")
        self.menuFile.addAction(self.actionLoad_Movie)
        self.menuFile.addAction(self.actionLoad_Parameters)
        self.menuFile.addAction(self.actionLoad_Locs1)
        self.menuFile.addAction(self.actionLoad_Locs2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Parameters)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSet_DaoSTORM_path)
        self.menuFile.addAction(self.actionCapture)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visualizer"))
        self.movieGroupBox.setTitle(_translate("MainWindow", "Movie"))
        self.doFit.setText(_translate("MainWindow", "Fit"))
        self.rangeGroupBox.setTitle(_translate("MainWindow", "Contrast"))
        self.nmPerPixLabel.setText(_translate("MainWindow", "nm per pixel:"))
        self.frameLabel.setText(_translate("MainWindow", "NA"))
        self.xyiLabel.setText(_translate("MainWindow", "NA"))
        self.analyze_current_dax.setText(_translate("MainWindow", "Fit current DAX"))
        self.batch_dax.setText(_translate("MainWindow", "Batch fit"))
        self.fileLabel.setText(_translate("MainWindow", "DAX file"))
        self.localization_groupbox.setTitle(_translate("MainWindow", "Localization Fit Parameters"))
        self.groupBox_2.setTitle(_translate("MainWindow", "General"))
        self.label.setText(_translate("MainWindow", "Method"))
        self.fit_fittype.setItemText(0, _translate("MainWindow", "2d"))
        self.fit_fittype.setItemText(1, _translate("MainWindow", "2dfixed"))
        self.fit_fittype.setItemText(2, _translate("MainWindow", "3d"))
        self.fit_fittype.setItemText(3, _translate("MainWindow", "Z"))
        self.label_2.setText(_translate("MainWindow", "Threshold"))
        self.label_3.setText(_translate("MainWindow", "Max iterations"))
        self.label_4.setText(_translate("MainWindow", "CCD background"))
        self.label_5.setText(_translate("MainWindow", "CCD pixel size"))
        self.label_6.setText(_translate("MainWindow", "Camera gain"))
        self.label_7.setText(_translate("MainWindow", "Background sigma"))
        self.label_8.setText(_translate("MainWindow", "Initial fit width"))
        self.label_9.setText(_translate("MainWindow", "Max find radius"))
        self.label_10.setText(_translate("MainWindow", "Descriptor"))
        self.label_11.setText(_translate("MainWindow", "Max displacement (px)"))
        self.label_12.setText(_translate("MainWindow", "Start frame"))
        self.label_13.setText(_translate("MainWindow", "End frame"))
        self.groupBox_4.setTitle(_translate("MainWindow", "ROI"))
        self.label_17.setText(_translate("MainWindow", "x min"))
        self.label_18.setText(_translate("MainWindow", "x max"))
        self.label_19.setText(_translate("MainWindow", "y min"))
        self.label_20.setText(_translate("MainWindow", "y max"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drift"))
        self.label_14.setText(_translate("MainWindow", "Correct drift?"))
        self.label_15.setText(_translate("MainWindow", "d scale"))
        self.label_16.setText(_translate("MainWindow", "Frames per step"))
        self.label_40.setText(_translate("MainWindow", "Correct Z?"))
        self.zfit_groupbox.setTitle(_translate("MainWindow", "Z-fitting"))
        self.label_21.setText(_translate("MainWindow", "Fit 3d (3d mode only)"))
        self.label_22.setText(_translate("MainWindow", "z cutoff"))
        self.label_23.setText(_translate("MainWindow", "z calib start (um)"))
        self.label_24.setText(_translate("MainWindow", "z calib end (um)"))
        self.label_25.setText(_translate("MainWindow", "wx0"))
        self.label_26.setText(_translate("MainWindow", "gx"))
        self.label_27.setText(_translate("MainWindow", "zrx"))
        self.label_28.setText(_translate("MainWindow", "Ax"))
        self.label_29.setText(_translate("MainWindow", "Bx"))
        self.label_30.setText(_translate("MainWindow", "Cx"))
        self.label_31.setText(_translate("MainWindow", "Dx"))
        self.label_32.setText(_translate("MainWindow", "wy0"))
        self.label_33.setText(_translate("MainWindow", "gy"))
        self.label_34.setText(_translate("MainWindow", "zry"))
        self.label_35.setText(_translate("MainWindow", "Ay"))
        self.label_36.setText(_translate("MainWindow", "By"))
        self.label_37.setText(_translate("MainWindow", "Cy"))
        self.label_38.setText(_translate("MainWindow", "Dy"))
        self.fit_save.setText(_translate("MainWindow", "Save"))
        self.fit_load.setText(_translate("MainWindow", "Load"))
        self.label_39.setText(_translate("MainWindow", "z calib string"))
        self.importZcalibstring.setText(_translate("MainWindow", "Import"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stormfinder), _translate("MainWindow", "STORMfinder"))
        self.groupBox.setTitle(_translate("MainWindow", "Localization Fit Parameters"))
        self.locs1Label.setText(_translate("MainWindow", "Localizations 1 Results"))
        self.locs2Label.setText(_translate("MainWindow", "Localizations 2 Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_localizations), _translate("MainWindow", "Localizations"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Movie.setText(_translate("MainWindow", "Load Movie"))
        self.actionLoad_Locs2.setText(_translate("MainWindow", "Load Localizations 2"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLoad_Locs1.setText(_translate("MainWindow", "Load Localizations 1"))
        self.actionCapture.setText(_translate("MainWindow", "Frame Capture"))
        self.actionLoad_Parameters.setText(_translate("MainWindow", "Load Parameters"))
        self.actionSave_Parameters.setText(_translate("MainWindow", "Save parameters"))
        self.actionSet_DaoSTORM_path.setText(_translate("MainWindow", "Set DaoSTORM path"))

