# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1210, 883)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.movieGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieGroupBox.sizePolicy().hasHeightForWidth())
        self.movieGroupBox.setSizePolicy(sizePolicy)
        self.movieGroupBox.setObjectName("movieGroupBox")
        self.horizontalLayout.addWidget(self.movieGroupBox)
        self.rangeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.rangeGroupBox.setObjectName("rangeGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rangeGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.maxSpinBox = QtWidgets.QSpinBox(self.rangeGroupBox)
        self.maxSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.maxSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.maxSpinBox.setMaximum(100000)
        self.maxSpinBox.setProperty("value", 1000)
        self.maxSpinBox.setObjectName("maxSpinBox")
        self.verticalLayout_2.addWidget(self.maxSpinBox)
        self.rangeSliderWidget = QtWidgets.QWidget(self.rangeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSliderWidget.sizePolicy().hasHeightForWidth())
        self.rangeSliderWidget.setSizePolicy(sizePolicy)
        self.rangeSliderWidget.setMinimumSize(QtCore.QSize(45, 0))
        self.rangeSliderWidget.setMaximumSize(QtCore.QSize(45, 16777215))
        self.rangeSliderWidget.setObjectName("rangeSliderWidget")
        self.verticalLayout_2.addWidget(self.rangeSliderWidget)
        self.minSpinBox = QtWidgets.QSpinBox(self.rangeGroupBox)
        self.minSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.minSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.minSpinBox.setMaximum(100000)
        self.minSpinBox.setProperty("value", 100)
        self.minSpinBox.setObjectName("minSpinBox")
        self.verticalLayout_2.addWidget(self.minSpinBox)
        self.horizontalLayout.addWidget(self.rangeGroupBox)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.multiLabel = QtWidgets.QLabel(self.groupBox)
        self.multiLabel.setObjectName("multiLabel")
        self.verticalLayout.addWidget(self.multiLabel)
        self.multiTableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.multiTableWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.multiTableWidget.setShowGrid(True)
        self.multiTableWidget.setObjectName("multiTableWidget")
        self.multiTableWidget.setColumnCount(0)
        self.multiTableWidget.setRowCount(0)
        self.multiTableWidget.horizontalHeader().setVisible(False)
        self.multiTableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.multiTableWidget.horizontalHeader().setStretchLastSection(True)
        self.multiTableWidget.verticalHeader().setVisible(False)
        self.multiTableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.multiTableWidget)
        self.i3Label = QtWidgets.QLabel(self.groupBox)
        self.i3Label.setObjectName("i3Label")
        self.verticalLayout.addWidget(self.i3Label)
        self.i3TableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.i3TableWidget.setShowGrid(True)
        self.i3TableWidget.setObjectName("i3TableWidget")
        self.i3TableWidget.setColumnCount(0)
        self.i3TableWidget.setRowCount(0)
        self.i3TableWidget.horizontalHeader().setVisible(False)
        self.i3TableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.i3TableWidget.horizontalHeader().setStretchLastSection(True)
        self.i3TableWidget.verticalHeader().setVisible(False)
        self.i3TableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.i3TableWidget)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nmPerPixLabel = QtWidgets.QLabel(self.centralwidget)
        self.nmPerPixLabel.setObjectName("nmPerPixLabel")
        self.horizontalLayout_2.addWidget(self.nmPerPixLabel)
        self.nmPerPixelSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.nmPerPixelSpinBox.setMaximum(1000.0)
        self.nmPerPixelSpinBox.setProperty("value", 160.0)
        self.nmPerPixelSpinBox.setObjectName("nmPerPixelSpinBox")
        self.horizontalLayout_2.addWidget(self.nmPerPixelSpinBox)
        self.oriCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.oriCheckBox.setMinimumSize(QtCore.QSize(90, 0))
        self.oriCheckBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.oriCheckBox.setObjectName("oriCheckBox")
        self.horizontalLayout_2.addWidget(self.oriCheckBox)
        self.frameLabel = QtWidgets.QLabel(self.centralwidget)
        self.frameLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.frameLabel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frameLabel.setObjectName("frameLabel")
        self.horizontalLayout_2.addWidget(self.frameLabel)
        self.xyiLabel = QtWidgets.QLabel(self.centralwidget)
        self.xyiLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.xyiLabel.setMaximumSize(QtCore.QSize(0, 16777215))
        self.xyiLabel.setScaledContents(False)
        self.xyiLabel.setObjectName("xyiLabel")
        self.horizontalLayout_2.addWidget(self.xyiLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLabel.sizePolicy().hasHeightForWidth())
        self.fileLabel.setSizePolicy(sizePolicy)
        self.fileLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.fileLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout_2.addWidget(self.fileLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1210, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Movie = QtWidgets.QAction(MainWindow)
        self.actionLoad_Movie.setObjectName("actionLoad_Movie")
        self.actionLoad_Insight3_Locs = QtWidgets.QAction(MainWindow)
        self.actionLoad_Insight3_Locs.setObjectName("actionLoad_Insight3_Locs")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLoad_3DDAO_Locs = QtWidgets.QAction(MainWindow)
        self.actionLoad_3DDAO_Locs.setObjectName("actionLoad_3DDAO_Locs")
        self.actionCapture = QtWidgets.QAction(MainWindow)
        self.actionCapture.setObjectName("actionCapture")
        self.menuFile.addAction(self.actionLoad_Movie)
        self.menuFile.addAction(self.actionLoad_3DDAO_Locs)
        self.menuFile.addAction(self.actionLoad_Insight3_Locs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCapture)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visualizer"))
        self.movieGroupBox.setTitle(_translate("MainWindow", "Movie"))
        self.rangeGroupBox.setTitle(_translate("MainWindow", "Contrast"))
        self.groupBox.setTitle(_translate("MainWindow", "Localization Fit Parameters"))
        self.multiLabel.setText(_translate("MainWindow", "3D-DAOSTORM Fit Results:"))
        self.i3Label.setText(_translate("MainWindow", "Insight3 Fit Results:"))
        self.nmPerPixLabel.setText(_translate("MainWindow", "nm per pixel:"))
        self.oriCheckBox.setText(_translate("MainWindow", "Inverted"))
        self.frameLabel.setText(_translate("MainWindow", "NA"))
        self.xyiLabel.setText(_translate("MainWindow", "NA"))
        self.fileLabel.setText(_translate("MainWindow", "NA"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Movie.setText(_translate("MainWindow", "Load Movie"))
        self.actionLoad_Insight3_Locs.setText(_translate("MainWindow", "Load Insight3 Results"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionLoad_3DDAO_Locs.setText(_translate("MainWindow", "Load 3D-DAOSTORM Results"))
        self.actionCapture.setText(_translate("MainWindow", "Frame Capture"))

