# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualizer.ui'
#
# Created: Tue Jun 11 14:08:01 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(972, 674)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.movieGroupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movieGroupBox.sizePolicy().hasHeightForWidth())
        self.movieGroupBox.setSizePolicy(sizePolicy)
        self.movieGroupBox.setObjectName(_fromUtf8("movieGroupBox"))
        self.horizontalLayout.addWidget(self.movieGroupBox)
        self.rangeGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.rangeGroupBox.setObjectName(_fromUtf8("rangeGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.rangeGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.maxSpinBox = QtGui.QSpinBox(self.rangeGroupBox)
        self.maxSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.maxSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.maxSpinBox.setMaximum(20000)
        self.maxSpinBox.setProperty("value", 1000)
        self.maxSpinBox.setObjectName(_fromUtf8("maxSpinBox"))
        self.verticalLayout_2.addWidget(self.maxSpinBox)
        self.rangeSliderWidget = QtGui.QWidget(self.rangeGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSliderWidget.sizePolicy().hasHeightForWidth())
        self.rangeSliderWidget.setSizePolicy(sizePolicy)
        self.rangeSliderWidget.setMinimumSize(QtCore.QSize(45, 0))
        self.rangeSliderWidget.setMaximumSize(QtCore.QSize(45, 16777215))
        self.rangeSliderWidget.setObjectName(_fromUtf8("rangeSliderWidget"))
        self.verticalLayout_2.addWidget(self.rangeSliderWidget)
        self.minSpinBox = QtGui.QSpinBox(self.rangeGroupBox)
        self.minSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.minSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.minSpinBox.setMaximum(20000)
        self.minSpinBox.setProperty("value", 100)
        self.minSpinBox.setObjectName(_fromUtf8("minSpinBox"))
        self.verticalLayout_2.addWidget(self.minSpinBox)
        self.horizontalLayout.addWidget(self.rangeGroupBox)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.multiLabel = QtGui.QLabel(self.groupBox)
        self.multiLabel.setObjectName(_fromUtf8("multiLabel"))
        self.verticalLayout.addWidget(self.multiLabel)
        self.multiTableWidget = QtGui.QTableWidget(self.groupBox)
        self.multiTableWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.multiTableWidget.setShowGrid(True)
        self.multiTableWidget.setObjectName(_fromUtf8("multiTableWidget"))
        self.multiTableWidget.setColumnCount(0)
        self.multiTableWidget.setRowCount(0)
        self.multiTableWidget.horizontalHeader().setVisible(False)
        self.multiTableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.multiTableWidget.horizontalHeader().setStretchLastSection(True)
        self.multiTableWidget.verticalHeader().setVisible(False)
        self.multiTableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.multiTableWidget)
        self.i3Label = QtGui.QLabel(self.groupBox)
        self.i3Label.setObjectName(_fromUtf8("i3Label"))
        self.verticalLayout.addWidget(self.i3Label)
        self.i3TableWidget = QtGui.QTableWidget(self.groupBox)
        self.i3TableWidget.setShowGrid(True)
        self.i3TableWidget.setObjectName(_fromUtf8("i3TableWidget"))
        self.i3TableWidget.setColumnCount(0)
        self.i3TableWidget.setRowCount(0)
        self.i3TableWidget.horizontalHeader().setVisible(False)
        self.i3TableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.i3TableWidget.horizontalHeader().setStretchLastSection(True)
        self.i3TableWidget.verticalHeader().setVisible(False)
        self.i3TableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.i3TableWidget)
        self.horizontalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.nmPerPixLabel = QtGui.QLabel(self.centralwidget)
        self.nmPerPixLabel.setObjectName(_fromUtf8("nmPerPixLabel"))
        self.horizontalLayout_2.addWidget(self.nmPerPixLabel)
        self.nmPerPixelSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.nmPerPixelSpinBox.setMaximum(1000.0)
        self.nmPerPixelSpinBox.setProperty("value", 160.0)
        self.nmPerPixelSpinBox.setObjectName(_fromUtf8("nmPerPixelSpinBox"))
        self.horizontalLayout_2.addWidget(self.nmPerPixelSpinBox)
        self.oriCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.oriCheckBox.setMinimumSize(QtCore.QSize(80, 0))
        self.oriCheckBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.oriCheckBox.setObjectName(_fromUtf8("oriCheckBox"))
        self.horizontalLayout_2.addWidget(self.oriCheckBox)
        self.frameLabel = QtGui.QLabel(self.centralwidget)
        self.frameLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.frameLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frameLabel.setObjectName(_fromUtf8("frameLabel"))
        self.horizontalLayout_2.addWidget(self.frameLabel)
        self.xyiLabel = QtGui.QLabel(self.centralwidget)
        self.xyiLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.xyiLabel.setMaximumSize(QtCore.QSize(140, 16777215))
        self.xyiLabel.setObjectName(_fromUtf8("xyiLabel"))
        self.horizontalLayout_2.addWidget(self.xyiLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.fileLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLabel.sizePolicy().hasHeightForWidth())
        self.fileLabel.setSizePolicy(sizePolicy)
        self.fileLabel.setMinimumSize(QtCore.QSize(300, 0))
        self.fileLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.fileLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.horizontalLayout_2.addWidget(self.fileLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 972, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Movie = QtGui.QAction(MainWindow)
        self.actionLoad_Movie.setObjectName(_fromUtf8("actionLoad_Movie"))
        self.actionLoad_Insight3_Locs = QtGui.QAction(MainWindow)
        self.actionLoad_Insight3_Locs.setObjectName(_fromUtf8("actionLoad_Insight3_Locs"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionLoad_3DDAO_Locs = QtGui.QAction(MainWindow)
        self.actionLoad_3DDAO_Locs.setObjectName(_fromUtf8("actionLoad_3DDAO_Locs"))
        self.actionCapture = QtGui.QAction(MainWindow)
        self.actionCapture.setObjectName(_fromUtf8("actionCapture"))
        self.menuFile.addAction(self.actionLoad_Movie)
        self.menuFile.addAction(self.actionLoad_3DDAO_Locs)
        self.menuFile.addAction(self.actionLoad_Insight3_Locs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCapture)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Visualizer", None))
        self.movieGroupBox.setTitle(_translate("MainWindow", "Movie", None))
        self.rangeGroupBox.setTitle(_translate("MainWindow", "Contrast", None))
        self.groupBox.setTitle(_translate("MainWindow", "Localization Fit Parameters", None))
        self.multiLabel.setText(_translate("MainWindow", "3D-DAOSTORM Fit Results:", None))
        self.i3Label.setText(_translate("MainWindow", "Insight3 Fit Results:", None))
        self.nmPerPixLabel.setText(_translate("MainWindow", "nm per pixel:", None))
        self.oriCheckBox.setText(_translate("MainWindow", "Inverted", None))
        self.frameLabel.setText(_translate("MainWindow", "NA", None))
        self.xyiLabel.setText(_translate("MainWindow", "NA", None))
        self.fileLabel.setText(_translate("MainWindow", "NA", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionLoad_Movie.setText(_translate("MainWindow", "Load Movie", None))
        self.actionLoad_Insight3_Locs.setText(_translate("MainWindow", "Load Insight3 Results", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionLoad_3DDAO_Locs.setText(_translate("MainWindow", "Load 3D-DAOSTORM Results", None))
        self.actionCapture.setText(_translate("MainWindow", "Frame Capture", None))

